<?php

namespace Standards\Countries\Iso_3166_1_Alpha_2;

enum Country: string
{
    case Andorra = 'AD'; // Andorra
    case UnitedArabEmirates = 'AE'; // United Arab Emirates
    case Afghanistan = 'AF'; // Afghanistan
    case AntiguaAndBarbuda = 'AG'; // Antigua and Barbuda
    case Anguilla = 'AI'; // Anguilla
    case Albania = 'AL'; // Albania
    case Armenia = 'AM'; // Armenia
    case Angola = 'AO'; // Angola
    case Antarctica = 'AQ'; // Antarctica
    case Argentina = 'AR'; // Argentina
    case AmericanSamoa = 'AS'; // American Samoa
    case Austria = 'AT'; // Austria
    case Australia = 'AU'; // Australia
    case Aruba = 'AW'; // Aruba
    case AlandIslands = 'AX'; // Åland Islands
    case Azerbaijan = 'AZ'; // Azerbaijan
    case BosniaAndHerzegovina = 'BA'; // Bosnia and Herzegovina
    case Barbados = 'BB'; // Barbados
    case Bangladesh = 'BD'; // Bangladesh
    case Belgium = 'BE'; // Belgium
    case BurkinaFaso = 'BF'; // Burkina Faso
    case Bulgaria = 'BG'; // Bulgaria
    case Bahrain = 'BH'; // Bahrain
    case Burundi = 'BI'; // Burundi
    case Benin = 'BJ'; // Benin
    case SaintBarthelemy = 'BL'; // Saint Barthélemy
    case Bermuda = 'BM'; // Bermuda
    case Brunei = 'BN'; // Brunei
    case Bolivia = 'BO'; // Bolivia
    case CaribbeanNetherlands = 'BQ'; // Caribbean Netherlands
    case Brazil = 'BR'; // Brazil
    case Bahamas = 'BS'; // Bahamas
    case Bhutan = 'BT'; // Bhutan
    case BouvetIsland = 'BV'; // Bouvet Island
    case Botswana = 'BW'; // Botswana
    case Belarus = 'BY'; // Belarus
    case Belize = 'BZ'; // Belize
    case Canada = 'CA'; // Canada
    case CocosKeelingIslands = 'CC'; // Cocos (Keeling) Islands
    case DrCongo = 'CD'; // DR Congo
    case CentralAfricanRepublic = 'CF'; // Central African Republic
    case RepublicOfTheCongo = 'CG'; // Republic of the Congo
    case Switzerland = 'CH'; // Switzerland
    case IvoryCoast = 'CI'; // Ivory Coast
    case CookIslands = 'CK'; // Cook Islands
    case Chile = 'CL'; // Chile
    case Cameroon = 'CM'; // Cameroon
    case China = 'CN'; // China
    case Colombia = 'CO'; // Colombia
    case CostaRica = 'CR'; // Costa Rica
    case Cuba = 'CU'; // Cuba
    case CapeVerde = 'CV'; // Cape Verde
    case Curacao = 'CW'; // Curaçao
    case ChristmasIsland = 'CX'; // Christmas Island
    case Cyprus = 'CY'; // Cyprus
    case CzechRepublic = 'CZ'; // Czech Republic
    case Germany = 'DE'; // Germany
    case Djibouti = 'DJ'; // Djibouti
    case Denmark = 'DK'; // Denmark
    case Dominica = 'DM'; // Dominica
    case DominicanRepublic = 'DO'; // Dominican Republic
    case Algeria = 'DZ'; // Algeria
    case Ecuador = 'EC'; // Ecuador
    case Estonia = 'EE'; // Estonia
    case Egypt = 'EG'; // Egypt
    case WesternSahara = 'EH'; // Western Sahara
    case Eritrea = 'ER'; // Eritrea
    case Spain = 'ES'; // Spain
    case Ethiopia = 'ET'; // Ethiopia
    case Finland = 'FI'; // Finland
    case Fiji = 'FJ'; // Fiji
    case FalklandIslands = 'FK'; // Falkland Islands
    case Micronesia = 'FM'; // Micronesia
    case FaroeIslands = 'FO'; // Faroe Islands
    case France = 'FR'; // France
    case Gabon = 'GA'; // Gabon
    case UnitedKingdom = 'GB'; // United Kingdom
    case Grenada = 'GD'; // Grenada
    case Georgia = 'GE'; // Georgia
    case FrenchGuiana = 'GF'; // French Guiana
    case Guernsey = 'GG'; // Guernsey
    case Ghana = 'GH'; // Ghana
    case Gibraltar = 'GI'; // Gibraltar
    case Greenland = 'GL'; // Greenland
    case Gambia = 'GM'; // Gambia
    case Guinea = 'GN'; // Guinea
    case Guadeloupe = 'GP'; // Guadeloupe
    case EquatorialGuinea = 'GQ'; // Equatorial Guinea
    case Greece = 'GR'; // Greece
    case SouthGeorgia = 'GS'; // South Georgia
    case Guatemala = 'GT'; // Guatemala
    case Guam = 'GU'; // Guam
    case GuineaBissau = 'GW'; // Guinea-Bissau
    case Guyana = 'GY'; // Guyana
    case HongKong = 'HK'; // Hong Kong
    case HeardIslandAndMcdonaldIslands = 'HM'; // Heard Island and McDonald Islands
    case Honduras = 'HN'; // Honduras
    case Croatia = 'HR'; // Croatia
    case Haiti = 'HT'; // Haiti
    case Hungary = 'HU'; // Hungary
    case Indonesia = 'ID'; // Indonesia
    case Ireland = 'IE'; // Ireland
    case Israel = 'IL'; // Israel
    case IsleOfMan = 'IM'; // Isle of Man
    case India = 'IN'; // India
    case BritishIndianOceanTerritory = 'IO'; // British Indian Ocean Territory
    case Iraq = 'IQ'; // Iraq
    case Iran = 'IR'; // Iran
    case Iceland = 'IS'; // Iceland
    case Italy = 'IT'; // Italy
    case Jersey = 'JE'; // Jersey
    case Jamaica = 'JM'; // Jamaica
    case Jordan = 'JO'; // Jordan
    case Japan = 'JP'; // Japan
    case Kenya = 'KE'; // Kenya
    case Kyrgyzstan = 'KG'; // Kyrgyzstan
    case Cambodia = 'KH'; // Cambodia
    case Kiribati = 'KI'; // Kiribati
    case Comoros = 'KM'; // Comoros
    case SaintKittsAndNevis = 'KN'; // Saint Kitts and Nevis
    case NorthKorea = 'KP'; // North Korea
    case SouthKorea = 'KR'; // South Korea
    case Kuwait = 'KW'; // Kuwait
    case CaymanIslands = 'KY'; // Cayman Islands
    case Kazakhstan = 'KZ'; // Kazakhstan
    case Laos = 'LA'; // Laos
    case Lebanon = 'LB'; // Lebanon
    case SaintLucia = 'LC'; // Saint Lucia
    case Liechtenstein = 'LI'; // Liechtenstein
    case SriLanka = 'LK'; // Sri Lanka
    case Liberia = 'LR'; // Liberia
    case Lesotho = 'LS'; // Lesotho
    case Lithuania = 'LT'; // Lithuania
    case Luxembourg = 'LU'; // Luxembourg
    case Latvia = 'LV'; // Latvia
    case Libya = 'LY'; // Libya
    case Morocco = 'MA'; // Morocco
    case Monaco = 'MC'; // Monaco
    case Moldova = 'MD'; // Moldova
    case Montenegro = 'ME'; // Montenegro
    case SaintMartin = 'MF'; // Saint Martin
    case Madagascar = 'MG'; // Madagascar
    case MarshallIslands = 'MH'; // Marshall Islands
    case Macedonia = 'MK'; // Macedonia
    case Mali = 'ML'; // Mali
    case Myanmar = 'MM'; // Myanmar
    case Mongolia = 'MN'; // Mongolia
    case Macau = 'MO'; // Macau
    case NorthernMarianaIslands = 'MP'; // Northern Mariana Islands
    case Martinique = 'MQ'; // Martinique
    case Mauritania = 'MR'; // Mauritania
    case Montserrat = 'MS'; // Montserrat
    case Malta = 'MT'; // Malta
    case Mauritius = 'MU'; // Mauritius
    case Maldives = 'MV'; // Maldives
    case Malawi = 'MW'; // Malawi
    case Mexico = 'MX'; // Mexico
    case Malaysia = 'MY'; // Malaysia
    case Mozambique = 'MZ'; // Mozambique
    case Namibia = 'NA'; // Namibia
    case NewCaledonia = 'NC'; // New Caledonia
    case Niger = 'NE'; // Niger
    case NorfolkIsland = 'NF'; // Norfolk Island
    case Nigeria = 'NG'; // Nigeria
    case Nicaragua = 'NI'; // Nicaragua
    case Netherlands = 'NL'; // Netherlands
    case Norway = 'NO'; // Norway
    case Nepal = 'NP'; // Nepal
    case Nauru = 'NR'; // Nauru
    case Niue = 'NU'; // Niue
    case NewZealand = 'NZ'; // New Zealand
    case Oman = 'OM'; // Oman
    case Panama = 'PA'; // Panama
    case Peru = 'PE'; // Peru
    case FrenchPolynesia = 'PF'; // French Polynesia
    case PapuaNewGuinea = 'PG'; // Papua New Guinea
    case Philippines = 'PH'; // Philippines
    case Pakistan = 'PK'; // Pakistan
    case Poland = 'PL'; // Poland
    case SaintPierreAndMiquelon = 'PM'; // Saint Pierre and Miquelon
    case PitcairnIslands = 'PN'; // Pitcairn Islands
    case PuertoRico = 'PR'; // Puerto Rico
    case Palestine = 'PS'; // Palestine
    case Portugal = 'PT'; // Portugal
    case Palau = 'PW'; // Palau
    case Paraguay = 'PY'; // Paraguay
    case Qatar = 'QA'; // Qatar
    case Reunion = 'RE'; // Réunion
    case Romania = 'RO'; // Romania
    case Serbia = 'RS'; // Serbia
    case Russia = 'RU'; // Russia
    case Rwanda = 'RW'; // Rwanda
    case SaudiArabia = 'SA'; // Saudi Arabia
    case SolomonIslands = 'SB'; // Solomon Islands
    case Seychelles = 'SC'; // Seychelles
    case Sudan = 'SD'; // Sudan
    case Sweden = 'SE'; // Sweden
    case Singapore = 'SG'; // Singapore
    case SaintHelena = 'SH'; // Saint Helena
    case Slovenia = 'SI'; // Slovenia
    case SvalbardAndJanMayen = 'SJ'; // Svalbard and Jan Mayen
    case Slovakia = 'SK'; // Slovakia
    case SierraLeone = 'SL'; // Sierra Leone
    case SanMarino = 'SM'; // San Marino
    case Senegal = 'SN'; // Senegal
    case Somalia = 'SO'; // Somalia
    case Suriname = 'SR'; // Suriname
    case SouthSudan = 'SS'; // South Sudan
    case SaoTomeAndPrincipe = 'ST'; // São Tomé and Príncipe
    case ElSalvador = 'SV'; // El Salvador
    case SintMaarten = 'SX'; // Sint Maarten
    case Syria = 'SY'; // Syria
    case Swaziland = 'SZ'; // Swaziland
    case TurksAndCaicosIslands = 'TC'; // Turks and Caicos Islands
    case Chad = 'TD'; // Chad
    case FrenchSouthernAndAntarcticLands = 'TF'; // French Southern and Antarctic Lands
    case Togo = 'TG'; // Togo
    case Thailand = 'TH'; // Thailand
    case Tajikistan = 'TJ'; // Tajikistan
    case Tokelau = 'TK'; // Tokelau
    case TimorLeste = 'TL'; // Timor-Leste
    case Turkmenistan = 'TM'; // Turkmenistan
    case Tunisia = 'TN'; // Tunisia
    case Tonga = 'TO'; // Tonga
    case Turkey = 'TR'; // Turkey
    case TrinidadAndTobago = 'TT'; // Trinidad and Tobago
    case Tuvalu = 'TV'; // Tuvalu
    case Taiwan = 'TW'; // Taiwan
    case Tanzania = 'TZ'; // Tanzania
    case Ukraine = 'UA'; // Ukraine
    case Uganda = 'UG'; // Uganda
    case UnitedStatesMinorOutlyingIslands = 'UM'; // United States Minor Outlying Islands
    case UnitedStates = 'US'; // United States
    case Uruguay = 'UY'; // Uruguay
    case Uzbekistan = 'UZ'; // Uzbekistan
    case VaticanCity = 'VA'; // Vatican City
    case SaintVincentAndTheGrenadines = 'VC'; // Saint Vincent and the Grenadines
    case Venezuela = 'VE'; // Venezuela
    case BritishVirginIslands = 'VG'; // British Virgin Islands
    case UnitedStatesVirginIslands = 'VI'; // United States Virgin Islands
    case Vietnam = 'VN'; // Vietnam
    case Vanuatu = 'VU'; // Vanuatu
    case WallisAndFutuna = 'WF'; // Wallis and Futuna
    case Samoa = 'WS'; // Samoa
    case Kosovo = 'XK'; // Kosovo
    case Yemen = 'YE'; // Yemen
    case Mayotte = 'YT'; // Mayotte
    case SouthAfrica = 'ZA'; // South Africa
    case Zambia = 'ZM'; // Zambia
    case Zimbabwe = 'ZW'; // Zimbabwe

}
