<?php

namespace Standards\Countries\ISO_3166_1_Alpha_3;

enum Country: string
{
    case Andorra = 'AND'; // Andorra
    case UnitedArabEmirates = 'ARE'; // United Arab Emirates
    case Afghanistan = 'AFG'; // Afghanistan
    case AntiguaAndBarbuda = 'ATG'; // Antigua and Barbuda
    case Anguilla = 'AIA'; // Anguilla
    case Albania = 'ALB'; // Albania
    case Armenia = 'ARM'; // Armenia
    case Angola = 'AGO'; // Angola
    case Antarctica = 'ATA'; // Antarctica
    case Argentina = 'ARG'; // Argentina
    case AmericanSamoa = 'ASM'; // American Samoa
    case Austria = 'AUT'; // Austria
    case Australia = 'AUS'; // Australia
    case Aruba = 'ABW'; // Aruba
    case AlandIslands = 'ALA'; // Åland Islands
    case Azerbaijan = 'AZE'; // Azerbaijan
    case BosniaAndHerzegovina = 'BIH'; // Bosnia and Herzegovina
    case Barbados = 'BRB'; // Barbados
    case Bangladesh = 'BGD'; // Bangladesh
    case Belgium = 'BEL'; // Belgium
    case BurkinaFaso = 'BFA'; // Burkina Faso
    case Bulgaria = 'BGR'; // Bulgaria
    case Bahrain = 'BHR'; // Bahrain
    case Burundi = 'BDI'; // Burundi
    case Benin = 'BEN'; // Benin
    case SaintBarthelemy = 'BLM'; // Saint Barthélemy
    case Bermuda = 'BMU'; // Bermuda
    case Brunei = 'BRN'; // Brunei
    case Bolivia = 'BOL'; // Bolivia
    case CaribbeanNetherlands = 'BES'; // Caribbean Netherlands
    case Brazil = 'BRA'; // Brazil
    case Bahamas = 'BHS'; // Bahamas
    case Bhutan = 'BTN'; // Bhutan
    case BouvetIsland = 'BVT'; // Bouvet Island
    case Botswana = 'BWA'; // Botswana
    case Belarus = 'BLR'; // Belarus
    case Belize = 'BLZ'; // Belize
    case Canada = 'CAN'; // Canada
    case CocosKeelingIslands = 'CCK'; // Cocos (Keeling) Islands
    case DrCongo = 'COD'; // DR Congo
    case CentralAfricanRepublic = 'CAF'; // Central African Republic
    case RepublicOfTheCongo = 'COG'; // Republic of the Congo
    case Switzerland = 'CHE'; // Switzerland
    case IvoryCoast = 'CIV'; // Ivory Coast
    case CookIslands = 'COK'; // Cook Islands
    case Chile = 'CHL'; // Chile
    case Cameroon = 'CMR'; // Cameroon
    case China = 'CHN'; // China
    case Colombia = 'COL'; // Colombia
    case CostaRica = 'CRI'; // Costa Rica
    case Cuba = 'CUB'; // Cuba
    case CapeVerde = 'CPV'; // Cape Verde
    case Curacao = 'CUW'; // Curaçao
    case ChristmasIsland = 'CXR'; // Christmas Island
    case Cyprus = 'CYP'; // Cyprus
    case CzechRepublic = 'CZE'; // Czech Republic
    case Germany = 'DEU'; // Germany
    case Djibouti = 'DJI'; // Djibouti
    case Denmark = 'DNK'; // Denmark
    case Dominica = 'DMA'; // Dominica
    case DominicanRepublic = 'DOM'; // Dominican Republic
    case Algeria = 'DZA'; // Algeria
    case Ecuador = 'ECU'; // Ecuador
    case Estonia = 'EST'; // Estonia
    case Egypt = 'EGY'; // Egypt
    case WesternSahara = 'ESH'; // Western Sahara
    case Eritrea = 'ERI'; // Eritrea
    case Spain = 'ESP'; // Spain
    case Ethiopia = 'ETH'; // Ethiopia
    case Finland = 'FIN'; // Finland
    case Fiji = 'FJI'; // Fiji
    case FalklandIslands = 'FLK'; // Falkland Islands
    case Micronesia = 'FSM'; // Micronesia
    case FaroeIslands = 'FRO'; // Faroe Islands
    case France = 'FRA'; // France
    case Gabon = 'GAB'; // Gabon
    case UnitedKingdom = 'GBR'; // United Kingdom
    case Grenada = 'GRD'; // Grenada
    case Georgia = 'GEO'; // Georgia
    case FrenchGuiana = 'GUF'; // French Guiana
    case Guernsey = 'GGY'; // Guernsey
    case Ghana = 'GHA'; // Ghana
    case Gibraltar = 'GIB'; // Gibraltar
    case Greenland = 'GRL'; // Greenland
    case Gambia = 'GMB'; // Gambia
    case Guinea = 'GIN'; // Guinea
    case Guadeloupe = 'GLP'; // Guadeloupe
    case EquatorialGuinea = 'GNQ'; // Equatorial Guinea
    case Greece = 'GRC'; // Greece
    case SouthGeorgia = 'SGS'; // South Georgia
    case Guatemala = 'GTM'; // Guatemala
    case Guam = 'GUM'; // Guam
    case GuineaBissau = 'GNB'; // Guinea-Bissau
    case Guyana = 'GUY'; // Guyana
    case HongKong = 'HKG'; // Hong Kong
    case HeardIslandAndMcdonaldIslands = 'HMD'; // Heard Island and McDonald Islands
    case Honduras = 'HND'; // Honduras
    case Croatia = 'HRV'; // Croatia
    case Haiti = 'HTI'; // Haiti
    case Hungary = 'HUN'; // Hungary
    case Indonesia = 'IDN'; // Indonesia
    case Ireland = 'IRL'; // Ireland
    case Israel = 'ISR'; // Israel
    case IsleOfMan = 'IMN'; // Isle of Man
    case India = 'IND'; // India
    case BritishIndianOceanTerritory = 'IOT'; // British Indian Ocean Territory
    case Iraq = 'IRQ'; // Iraq
    case Iran = 'IRN'; // Iran
    case Iceland = 'ISL'; // Iceland
    case Italy = 'ITA'; // Italy
    case Jersey = 'JEY'; // Jersey
    case Jamaica = 'JAM'; // Jamaica
    case Jordan = 'JOR'; // Jordan
    case Japan = 'JPN'; // Japan
    case Kenya = 'KEN'; // Kenya
    case Kyrgyzstan = 'KGZ'; // Kyrgyzstan
    case Cambodia = 'KHM'; // Cambodia
    case Kiribati = 'KIR'; // Kiribati
    case Comoros = 'COM'; // Comoros
    case SaintKittsAndNevis = 'KNA'; // Saint Kitts and Nevis
    case NorthKorea = 'PRK'; // North Korea
    case SouthKorea = 'KOR'; // South Korea
    case Kuwait = 'KWT'; // Kuwait
    case CaymanIslands = 'CYM'; // Cayman Islands
    case Kazakhstan = 'KAZ'; // Kazakhstan
    case Laos = 'LAO'; // Laos
    case Lebanon = 'LBN'; // Lebanon
    case SaintLucia = 'LCA'; // Saint Lucia
    case Liechtenstein = 'LIE'; // Liechtenstein
    case SriLanka = 'LKA'; // Sri Lanka
    case Liberia = 'LBR'; // Liberia
    case Lesotho = 'LSO'; // Lesotho
    case Lithuania = 'LTU'; // Lithuania
    case Luxembourg = 'LUX'; // Luxembourg
    case Latvia = 'LVA'; // Latvia
    case Libya = 'LBY'; // Libya
    case Morocco = 'MAR'; // Morocco
    case Monaco = 'MCO'; // Monaco
    case Moldova = 'MDA'; // Moldova
    case Montenegro = 'MNE'; // Montenegro
    case SaintMartin = 'MAF'; // Saint Martin
    case Madagascar = 'MDG'; // Madagascar
    case MarshallIslands = 'MHL'; // Marshall Islands
    case Macedonia = 'MKD'; // Macedonia
    case Mali = 'MLI'; // Mali
    case Myanmar = 'MMR'; // Myanmar
    case Mongolia = 'MNG'; // Mongolia
    case Macau = 'MAC'; // Macau
    case NorthernMarianaIslands = 'MNP'; // Northern Mariana Islands
    case Martinique = 'MTQ'; // Martinique
    case Mauritania = 'MRT'; // Mauritania
    case Montserrat = 'MSR'; // Montserrat
    case Malta = 'MLT'; // Malta
    case Mauritius = 'MUS'; // Mauritius
    case Maldives = 'MDV'; // Maldives
    case Malawi = 'MWI'; // Malawi
    case Mexico = 'MEX'; // Mexico
    case Malaysia = 'MYS'; // Malaysia
    case Mozambique = 'MOZ'; // Mozambique
    case Namibia = 'NAM'; // Namibia
    case NewCaledonia = 'NCL'; // New Caledonia
    case Niger = 'NER'; // Niger
    case NorfolkIsland = 'NFK'; // Norfolk Island
    case Nigeria = 'NGA'; // Nigeria
    case Nicaragua = 'NIC'; // Nicaragua
    case Netherlands = 'NLD'; // Netherlands
    case Norway = 'NOR'; // Norway
    case Nepal = 'NPL'; // Nepal
    case Nauru = 'NRU'; // Nauru
    case Niue = 'NIU'; // Niue
    case NewZealand = 'NZL'; // New Zealand
    case Oman = 'OMN'; // Oman
    case Panama = 'PAN'; // Panama
    case Peru = 'PER'; // Peru
    case FrenchPolynesia = 'PYF'; // French Polynesia
    case PapuaNewGuinea = 'PNG'; // Papua New Guinea
    case Philippines = 'PHL'; // Philippines
    case Pakistan = 'PAK'; // Pakistan
    case Poland = 'POL'; // Poland
    case SaintPierreAndMiquelon = 'SPM'; // Saint Pierre and Miquelon
    case PitcairnIslands = 'PCN'; // Pitcairn Islands
    case PuertoRico = 'PRI'; // Puerto Rico
    case Palestine = 'PSE'; // Palestine
    case Portugal = 'PRT'; // Portugal
    case Palau = 'PLW'; // Palau
    case Paraguay = 'PRY'; // Paraguay
    case Qatar = 'QAT'; // Qatar
    case Reunion = 'REU'; // Réunion
    case Romania = 'ROU'; // Romania
    case Serbia = 'SRB'; // Serbia
    case Russia = 'RUS'; // Russia
    case Rwanda = 'RWA'; // Rwanda
    case SaudiArabia = 'SAU'; // Saudi Arabia
    case SolomonIslands = 'SLB'; // Solomon Islands
    case Seychelles = 'SYC'; // Seychelles
    case Sudan = 'SDN'; // Sudan
    case Sweden = 'SWE'; // Sweden
    case Singapore = 'SGP'; // Singapore
    case SaintHelena = 'SHN'; // Saint Helena
    case Slovenia = 'SVN'; // Slovenia
    case SvalbardAndJanMayen = 'SJM'; // Svalbard and Jan Mayen
    case Slovakia = 'SVK'; // Slovakia
    case SierraLeone = 'SLE'; // Sierra Leone
    case SanMarino = 'SMR'; // San Marino
    case Senegal = 'SEN'; // Senegal
    case Somalia = 'SOM'; // Somalia
    case Suriname = 'SUR'; // Suriname
    case SouthSudan = 'SSD'; // South Sudan
    case SaoTomeAndPrincipe = 'STP'; // São Tomé and Príncipe
    case ElSalvador = 'SLV'; // El Salvador
    case SintMaarten = 'SXM'; // Sint Maarten
    case Syria = 'SYR'; // Syria
    case Swaziland = 'SWZ'; // Swaziland
    case TurksAndCaicosIslands = 'TCA'; // Turks and Caicos Islands
    case Chad = 'TCD'; // Chad
    case FrenchSouthernAndAntarcticLands = 'ATF'; // French Southern and Antarctic Lands
    case Togo = 'TGO'; // Togo
    case Thailand = 'THA'; // Thailand
    case Tajikistan = 'TJK'; // Tajikistan
    case Tokelau = 'TKL'; // Tokelau
    case TimorLeste = 'TLS'; // Timor-Leste
    case Turkmenistan = 'TKM'; // Turkmenistan
    case Tunisia = 'TUN'; // Tunisia
    case Tonga = 'TON'; // Tonga
    case Turkey = 'TUR'; // Turkey
    case TrinidadAndTobago = 'TTO'; // Trinidad and Tobago
    case Tuvalu = 'TUV'; // Tuvalu
    case Taiwan = 'TWN'; // Taiwan
    case Tanzania = 'TZA'; // Tanzania
    case Ukraine = 'UKR'; // Ukraine
    case Uganda = 'UGA'; // Uganda
    case UnitedStatesMinorOutlyingIslands = 'UMI'; // United States Minor Outlying Islands
    case UnitedStates = 'USA'; // United States
    case Uruguay = 'URY'; // Uruguay
    case Uzbekistan = 'UZB'; // Uzbekistan
    case VaticanCity = 'VAT'; // Vatican City
    case SaintVincentAndTheGrenadines = 'VCT'; // Saint Vincent and the Grenadines
    case Venezuela = 'VEN'; // Venezuela
    case BritishVirginIslands = 'VGB'; // British Virgin Islands
    case UnitedStatesVirginIslands = 'VIR'; // United States Virgin Islands
    case Vietnam = 'VNM'; // Vietnam
    case Vanuatu = 'VUT'; // Vanuatu
    case WallisAndFutuna = 'WLF'; // Wallis and Futuna
    case Samoa = 'WSM'; // Samoa
    case Kosovo = 'UNK'; // Kosovo
    case Yemen = 'YEM'; // Yemen
    case Mayotte = 'MYT'; // Mayotte
    case SouthAfrica = 'ZAF'; // South Africa
    case Zambia = 'ZMB'; // Zambia
    case Zimbabwe = 'ZWE'; // Zimbabwe

}
